# Generated by Django 3.2.5 on 2021-07-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('base', models.CharField(max_length=255)),
                ('compare', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('author_email', models.CharField(max_length=255, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'CLOSED'), (3, 'NMERGED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
