# Generated by Django 3.2.5 on 2021-07-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitwrapper', '0002_auto_20210714_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='author_email',
        ),
    ]
